-- sql/2026-08-24_fund_monthly_statements.sql
-- Additive-only. Run in Supabase SQL editor, then verify with the checks
-- at the bottom.
--
-- New table for NAV-administrator-reported funds with no daily broker feed
-- (e.g. 12-FLAGS — 12 Flags Cayman Feeder Fund, monthly Investor Statement
-- from NAV Fund Services). Keyed directly by strategy_id — one statement
-- stream per strategy, no separate "clients" table needed (unlike AXIA,
-- which can have multiple client/account pairs per strategy).

create table if not exists public.fund_monthly_statements (
  id                  bigint generated by default as identity primary key,
  strategy_id         bigint not null references public.strategies(id) on delete cascade,
  period_end_date     date not null,             -- statement's "Period Ended" date
  currency            text not null default 'USD', -- source statement currency

  beginning_balance   numeric not null,           -- MTD Beginning Balance
  additions           numeric not null default 0, -- MTD Additions
  redemptions         numeric not null default 0, -- MTD Redemptions
  net_income          numeric not null,           -- computed: ending - beginning - additions + redemptions
  ending_balance      numeric not null,            -- MTD Ending Balance (the number you key in)
  rate_of_return_pct  numeric not null,            -- computed: net_income / beginning_balance * 100

  fx_rate             numeric,                    -- GBP_USD OANDA monthly close (1 GBP = fx_rate USD)
  fx_rate_date        date,                        -- date of the candle actually used
  ending_balance_gbp  numeric,                     -- ending_balance / fx_rate — null until FX fetched

  notes               text,
  created_at          timestamptz not null default now(),

  unique (strategy_id, period_end_date)
);

create index if not exists idx_fund_monthly_statements_strategy
  on public.fund_monthly_statements (strategy_id, period_end_date desc);

comment on table public.fund_monthly_statements is
  'Monthly statement entries for NAV-administrator-reported funds (e.g. 12-FLAGS). One row per strategy per period. ending_balance_gbp feeds that strategy''s Current Equity in the Capital & Performance Overview once FX is fetched.';

-- ---------------------------------------------------------------------------
-- Verification (run after the above)
-- ---------------------------------------------------------------------------
-- 1. Table exists with correct columns:
--      select column_name, data_type from information_schema.columns
--      where table_name = 'fund_monthly_statements' order by ordinal_position;
-- 2. FK to strategies is valid:
--      select conname, confrelid::regclass from pg_constraint
--      where conrelid = 'public.fund_monthly_statements'::regclass and contype = 'f';
-- 3. Empty table, ready for entries:
--      select count(*) from public.fund_monthly_statements;   -- expect 0
