-- sql/2026-09-29_gtx_statements.sql
-- Additive-only. Run in Supabase SQL editor, then verify with the checks
-- at the bottom.
--
-- GlobalGTX tab (Analysis page). Stores ONLY the raw daily statement
-- emails (pasted text) + parsed JSON, plus one settings row. Positions,
-- fees, swaps, closes and reconciliation are all re-derived on every load
-- by backend/src/services/gtx_engine.py (stateless replay) — so there is
-- no positions table and nothing can drift out of sync.

create table if not exists public.gtx_statements (
  id           bigint generated by default as identity primary key,
  account      text not null default 'GTX0011-USD',  -- USD sub-account name from the statement
  stmt_date    date not null,                         -- date the statement email arrived (23:00)
  raw_text     text not null,                         -- exactly what was pasted
  parsed       jsonb not null,                        -- gtx_parser.parse_statement() output
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (account, stmt_date)
);

create index if not exists idx_gtx_statements_account_date
  on public.gtx_statements (account, stmt_date);

comment on table public.gtx_statements is
  'Global Trading X daily statement pastes. Source of truth for the GlobalGTX tab; engine replays these in date order.';

create table if not exists public.gtx_settings (
  id          smallint primary key default 1 check (id = 1),  -- single row
  settings    jsonb not null default '{}'::jsonb,              -- overrides of gtx_engine.DEFAULT_SETTINGS
  updated_at  timestamptz not null default now()
);

insert into public.gtx_settings (id, settings) values (1, '{}'::jsonb)
  on conflict (id) do nothing;

comment on table public.gtx_settings is
  'GlobalGTX engine parameter overrides (fee_per_unit, swap rates, day_count, margin_pct...). Empty = engine defaults.';

-- ---------------------------------------------------------------------------
-- Verification (run after the above)
-- ---------------------------------------------------------------------------
-- 1. Both tables exist:
--      select table_name from information_schema.tables
--      where table_schema = 'public' and table_name like 'gtx_%';
--      -- expect gtx_settings, gtx_statements
-- 2. Settings row seeded:
--      select * from public.gtx_settings;            -- expect id=1, settings={}
-- 3. Statements empty, ready for pastes:
--      select count(*) from public.gtx_statements;   -- expect 0
-- 4. Unique key present:
--      select conname from pg_constraint
--      where conrelid = 'public.gtx_statements'::regclass and contype = 'u';
